### ISSUE TITLE
테스트용 카드

### ISSUE THREAD

**Issue by psyoblade** [modulabs-ctrl/pommerman-2018#1]
이건 뭔가요?

**Comment by wonseokjung** [comment]
<img src="https://www.dropbox.com/s/j4dliwe9jz25nfq/Screenshot%202018-10-21%2013.57.55.png?raw=1">

**Comment by wonseokjung** [comment]
$S_t$

**Comment by wonseokjung** [comment]
마일스톤의 의미는 다음과 같습니다. 

<img src="https://www.dropbox.com/s/zky2pkjtbx1ole6/Screenshot%202018-10-21%2014.01.17.png?raw=1">

**Comment by wonseokjung** [comment]
할꼬야

**Comment by psyoblade** [comment]
테스트용 카드는 닫을게요
